# Generated by Django 5.0.1 on 2024-02-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Foydalanuvchi manzili / Адрес пользователя')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': ' Адрес ',
                'verbose_name_plural': ' Адреса ',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Admin FISH / Админ ФИО')),
                ('telegram', models.BigIntegerField(unique=True, verbose_name='Telegram ID / ИД телеграммы')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' Админ ',
                'verbose_name_plural': ' Админы ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi / Название категории')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi / Название категории')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi / Название категории')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' Категория ',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dastavka_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('_from', models.FloatField()),
                ('_to', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цены на доставки',
                'verbose_name_plural': 'Цены на доставку',
            },
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, verbose_name='Guruh ID / Группа ИД')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' Группа ',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="O'lchov birlik nomi/Название единицы измерения")),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name="O'lchov birlik nomi/Название единицы измерения")),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name="O'lchov birlik nomi/Название единицы измерения")),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Единицы измерения продукта',
                'verbose_name_plural': 'Единицы измерения продукта',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanuvchi (FIO) / Пользовательский (ФИО)')),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Foydalanuvchi nomeri / Номер пользователя')),
                ('telegram', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID / ИД телеграммыД')),
                ('lang', models.CharField(blank=True, max_length=2, null=True, verbose_name='Til / Язык')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti / Время создания')),
            ],
            options={
                'verbose_name': ' Пользователь ',
                'verbose_name_plural': ' Пользователи ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('payment_type', models.CharField(choices=[('0', "🟠 To'lov kutilmoqda"), ('1', "🟢 To'lov qilindi"), ('2', '🔴 Bekor qilindi')], max_length=55, verbose_name="To'lov holati")),
                ('pay_type', models.CharField(max_length=18)),
                ('admin_status', models.CharField(choices=[('0', '🟠 Tasdiqlash kutilmoqda'), ('1', '🟢 Tasdiqlandi'), ('2', '🔴 Bekor qilindi')], max_length=30, verbose_name='Admin STATUS')),
                ('status', models.BooleanField(default=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('a_status', models.CharField(max_length=50)),
                ('create_date', models.DateField(verbose_name='Yaratilgan vaqti')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.address', verbose_name='Foydalanuvchi manzili')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': ' Заказ ',
                'verbose_name_plural': ' Заказы ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mahsulot nomi / Наименование товара')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Mahsulot nomi / Наименование товара')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Mahsulot nomi / Наименование товара')),
                ('description', models.TextField(verbose_name="Mahsulot haqida ma'lumot / Информация о продукте")),
                ('description_uz', models.TextField(null=True, verbose_name="Mahsulot haqida ma'lumot / Информация о продукте")),
                ('description_ru', models.TextField(null=True, verbose_name="Mahsulot haqida ma'lumot / Информация о продукте")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mahsulot narxi / Цена продукта')),
                ('quantity', models.FloatField(default=0, verbose_name='Mahsulot hajmi / Oбъем продукта')),
                ('status', models.BooleanField(default=True, verbose_name='Mahsulot status / Статус продукта')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm / Изображение')),
                ('time', models.IntegerField(default=0, verbose_name="Mahsulot tayyor bo'lish vaqti / Время готовности продукта")),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='Kategoriya / Категория')),
                ('measure', models.ManyToManyField(to='user.measure', verbose_name="O'lchov birligi/Единица измерения")),
            ],
            options={
                'verbose_name': ' Продукт ',
                'verbose_name_plural': ' Продукты ',
            },
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Qiymatlar/Ценности')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.measure', verbose_name="O'lchov birligi/Единица измерения")),
            ],
            options={
                'verbose_name': 'Размеры продукта',
                'verbose_name_plural': 'Размеры продукта',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='Telefon nomer / Телефон номер')),
                ('code', models.CharField(max_length=6, verbose_name='SMS code / СМС-код')),
                ('status', models.BooleanField(default=False, verbose_name='Holati / Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Foydalanuvchi / Пользователь')),
            ],
            options={
                'verbose_name': ' SMS ',
                'verbose_name_plural': ' SMS ',
            },
        ),
        migrations.CreateModel(
            name='OrderSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('_type', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('create_date', models.DateField(verbose_name='Yaratilgan vaqti')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.product', verbose_name='Mahsulot ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': ' Backend ',
                'verbose_name_plural': ' Backend ',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product', verbose_name="Mahsulot ID'si")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Foydalanuvchi FISH / Пользовательский ФИО'),
        ),
    ]
