# Generated by Django 5.0.1 on 2025-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='a_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
