# Generated by Django 5.1.1 on 2025-03-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_order_a_status_alter_order_pay_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersale',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пользовательский ФИО'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Админ ФИО'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='telegram',
            field=models.BigIntegerField(unique=True, verbose_name='ИД телеграммы'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product', verbose_name='Идентификатор продукта'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='group_id',
            field=models.CharField(max_length=255, verbose_name='Группа ИД'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название единицы измерения'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название единицы измерения'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название единицы измерения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.address', verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_status',
            field=models.CharField(choices=[('0', '🟠 Ожидается подтверждение'), ('1', '🟢 Подтверждено'), ('2', '🔴 Отменено')], max_length=30, verbose_name='СТАТУС АДМИНИСТРАТОРА'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cтоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('0', '🟠 Ожидается платеж'), ('1', '🟢 Оплачено'), ('2', '🔴 Отменено')], max_length=55, verbose_name='Адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='create_date',
            field=models.DateField(verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.product', verbose_name='Продукта'),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.ManyToManyField(to='user.measure', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Oбъем продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Время готовности продукта'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.measure', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Ценности'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='code',
            field=models.CharField(max_length=6, verbose_name='СМС-код'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользовательский (ФИО)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Номер пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ИД телеграммы'),
        ),
    ]
